[#13] prevent download of private keys
maykinmedia/django-simple-certmanager pull request #14
Opened 2022-12-30 15:06 UTC by pi-sigma

Fixes #13 (partly)

- add client-side patch that removes link to private keys
- server-side patch needs to be added in [django-privates](https://github.com/sergei-maertens/django-privates)

2022-12-30 15:13 UTC, pi-sigma commented
At the moment, private keys can still be downloaded by modifying the URL in the address bar of the browser. To prevent this, the view for the private key should not be created. This can be achieved by modifying the `admin.PrivateMediaMixin.get_urls` method in django-privates. I tried to achieve the same result by overwriting that method in the `simple_certmanager.admin.CertificateAdmin` class, but to no avail.

2023-01-06 13:27 UTC, sergei-maertens requested changes

2023-01-06 13:27 UTC, sergei-maertens commented on tox.ini
> +  pyquery==2.0.0
please specify this dependency in `setup.cfg` like with the other test dependencies

2023-01-06 13:27 UTC, sergei-maertens commented on tests/test_admin.py
> +class AdminTests(TestCase):
for the next time - we prefer writing tests in pytest style for libraries, pytest-django provides many useful tools to make tests easier to read and maintain.

2023-01-06 13:27 UTC, sergei-maertens commented on tests/test_admin.py
> +        response = certificate_admin.changelist_view(request)
this is not the typical pattern to test views - this should ideally be reversing the admin URLs and using `self.client` to make requests.

2023-01-09 07:52 UTC, sergei-maertens approved these changes

2023-01-09 07:52 UTC, merged