[#15] validate private keys
maykinmedia/django-simple-certmanager pull request #16
Opened 2023-01-03 15:59 UTC by pi-sigma

Fixes #15

I added validators to the model fields `Certificate.private_key` as well as `Certificate.public_certificate` and refactored `forms.py`.

Alternatively, the validation could be added in `forms.py`, but I struggled with the resulting code duplication (there is already validation in place for `public_certificate`), hence the approach taken here seemed cleaner to me.

2023-01-03 17:07 UTC, sergei-maertens requested changes

2023-01-03 17:07 UTC, sergei-maertens commented on tests/test_certificates.py
> +        self.assertFalse(form.is_valid())
please make assertions about _which_ fields are invalid. it's easy to add functionality in the future which causes other validation errors that would make this assertion pass, and then regressions are possible because another field is failing validation.

2023-01-04 09:28 UTC, SilviaAmAm commented
This fix will prevent invalid keys from being uploaded in the future. However for environments where invalid keys have already been uploaded, the certificate page will still be broken. It would be great to add a fix also for this case, so that in these environments the invalid keys can be replaced from the Admin interface.

So this will need a test with invalid data already set up and a check that the admin still works. 

We possibly need also an indication of certificates with invalid keys? So they can more easily be found and replaced.

2023-01-04 10:31 UTC, pi-sigma commented
I replaced the function-based validators with classed-based validators.

2023-01-04 10:39 UTC, pi-sigma commented
@SilviaAmAm

Good idea. I wonder what's the best way to implement this without affecting future versions. The broken page can be fixed by wrapping `Certificate.context.use_privatekey` in a `try/except`, but do we want that for future versions as well (the upload of invalid keys should be prevented by the present fix)?

2023-01-04 10:49 UTC, sergei-maertens commented
> This fix will prevent invalid keys from being uploaded in the future. However for environments where invalid keys have already been uploaded, the certificate page will still be broken. It would be great to add a fix also for this case, so that in these environments the invalid keys can be replaced from the Admin interface.
> 
> So this will need a test with invalid data already set up and a check that the admin still works.
> 
> We possibly need also an indication of certificates with invalid keys? So they can more easily be found and replaced.

@pi-sigma please implement some robustness for this by caching the expected error and displaying some generic warning/hint. It's still possible to get corrupt data in the database/filesystem due to programmatically creating/loading invalid key/certificate pairs as the validators are bypassed in those flows (unless explicitly called).

2023-01-04 10:59 UTC, sergei-maertens requested changes

2023-01-04 10:59 UTC, sergei-maertens commented on simple_certmanager/validators.py
> +        return crypto.load_privatekey(file_type, file_content)
```suggestion
class AbstractSSLValidator(ABC):
    message = _("Invalid file provided.")
    code = "invalid"

    @abstractmethod
    def validate(self, file_content: bytes):  # pragma: no cover
        raise NotImplementedError

    def __call__(self, value):
        with value.open(mode="rb") as infile:
            try:
                self.validate(infile.read())
            except crypto.Error:
                raise ValidationError(self.message, code=self.code)


class PublicCertValidator(AbstractSSLValidator):
    message = _("Invalid file provided, expected a certificate in PEM format.")

    @staticmethod
    def validate(file_content: bytes):
        return crypto.load_certificate(crypto.FILETYPE_PEM, file_content)


class PrivateKeyValidator(AbstractSSLValidator):
    message = _("Invalid file provided, expected a private key in PEM format.")

    @staticmethod
    def validate(file_content: bytes):
        return crypto.load_privatekey(crypto.FILETYPE_PEM, file_content)
```

* adds the appropriate type hints here and there
* makes the error message localize to the private key/public cert validation allowing for full contextual translation to NL
* the validate function itself can be simplified to a staticmethod
* moved the `crypto.FILETYPE_PEM` to make code easier to follow
* the use of `ABC` is a bit overkill here... we do not expect to expose this validator as public API

2023-01-04 11:00 UTC, sergei-maertens requested changes
I'm also missing the update in setup.cfg to require at least django-privates 1.5.0

2023-01-06 14:10 UTC, pi-sigma commented
The admin is fixed. Tests added to ensure that the admin works in the presence of corrupted data and that the data is logged.

2023-01-10 10:40 UTC, sergei-maertens approved these changes

2023-01-10 10:40 UTC, merged